<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>NamelessTech Careers</title>
<div class="index-hero">
  <div class="index-hero-inner">
    <div class="welcome-to">
      <h1>Welcome</h1>
    </div>
    <div class="hero-logo">
      <a href="index.php">
        <img src="../images/image.png" alt="NamelessTech Logo" width="100" style="margin-bottom: 10px;">
      </a>
    </div>
    <div class="namelesstech-text">
      <h1>NamelessTech</h1>
    </div>
  </div>
</div>
