<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>NamelessTech Careers</title>
<div class="index-hero">
  <div class="welcome-to">
    <h1>NamelessTech</h1>
  </div>
  <div class="hero-logo">
    <a href="index.php">
      <img src="../images/image.png" alt="NamelessTech Logo" /> <!--Logo image was created with AI (Sora) with the instruction "draw a logo as symbol of NamelessTech" in chinese-->
    </a>
  </div>

</div>
