
<div class="nav-section">
  <nav>
    <ul>
      <li>
      <a href="index.php" class="nav-link">
      <span class="home-icon-wrapper">
          <svg class="home-icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 256 256" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="16" class="home-icon">
            <path d="M213.3815,109.61945,133.376,36.88436a8,8,0,0,0-10.76339.00036l-79.9945,72.73477A8,8,0,0,0,40,115.53855V208a8,8,0,0,0,8,8H208a8,8,0,0,0,8-8V115.53887A8,8,0,0,0,213.3815,109.61945Z"/>
          </svg> <!--Home Icon base-->
          <span class="nav-text">Home</span>
      </span>
      </a>
      </li>
      <li><a href="jobs.php">Jobs</a></li>
      <li><a href="apply.php">Apply</a></li>
      <li><a href="about.php">About Us</a></li>
      <li><a href="mailto:info@namelesstech.com.au" style="color: #5A3FA7;">Contact Us</a></li>
    </ul>
  </nav>
</div>
